apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-web
  template:
    metadata:
      labels:
        app: notes-web
    spec:
      containers:
      - name: notes-web
        image: notes-web:1.0
        imagePullPolicy: Never

        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: notes-web
spec:
  type: NodePort
  selector:
    app: notes-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
